### ISSUE TITLE
video system not initialized

### ISSUE THREAD

**Issue by distortia** [azah/IsaacStatTracker#1]
Attempting to run the .exe within the game folder as directed. The windows displays but my items/bosses are not updating

Things I have attempted: 
Restarting game
Loading game before application
Loading application before game

Attached is the error log
------------------------------------
Traceback (most recent call last):
  File "IsaacStatTracker.py", line 119, in <module>
pygame.error: video system not initialized

**Comment by azah** [comment]
Looks like it was due to calling displayGraphics(player) without actually checking if the player object exists. When Isaac is started, it wipes the log.txt so that's what would cause this.
Hotfix: Start ISTv0.1.3 after starting a new run in Isaac. As long as there is something in the file it won't throw that exception. 
Will fix for 0.1.3a or 0.1.4

**Comment by azah** [comment]
Okay I was totally wrong. What was happening was I forgot to include the pictures folder.  
The error being thrown was due to me calling `if event.type == QUIT:` instead of `if event.type == pygame.QUIT:`, resulting in the quit event never being realized in pygame, throwing that misleading error. Now, pygame.quit() and sys.exit() are being called, resulting in no error thrown.
